-- MySQL Script generated by MySQL Workbench
-- Tue Oct  3 19:47:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projetoExpoCeep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetoExpoCeep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoExpoCeep` DEFAULT CHARACTER SET utf8 ;
USE `projetoExpoCeep` ;

-- -----------------------------------------------------
-- Table `projetoExpoCeep`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoExpoCeep`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoExpoCeep`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoExpoCeep`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoExpoCeep`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoExpoCeep`.`projeto` (
  `idprojeto` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `modalida_proj` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `modalida_turno` VARCHAR(45) NOT NULL,
  `serieturma` VARCHAR(45) NOT NULL,
  `nome_coordenador` VARCHAR(45) NOT NULL,
  `area_proj` VARCHAR(45) NOT NULL,
  `idusuario` INT NOT NULL,
  `idcurso` INT NOT NULL,
  `caminhoImagemEnsalamento` VARCHAR(60) NULL,
  `ensalamento` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idprojeto`),
  INDEX `fk_projeto_usuario_idx` (`idusuario` ASC),
  INDEX `fk_projeto_curso1_idx` (`idcurso` ASC),
  CONSTRAINT `fk_projeto_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `projetoExpoCeep`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projeto_curso1`
    FOREIGN KEY (`idcurso`)
    REFERENCES `projetoExpoCeep`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoExpoCeep`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoExpoCeep`.`professor` (
  `idprofessor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `idprojeto` INT NOT NULL,
  PRIMARY KEY (`idprofessor`),
  INDEX `fk_professor_projeto1_idx` (`idprojeto` ASC),
  CONSTRAINT `fk_professor_projeto1`
    FOREIGN KEY (`idprojeto`)
    REFERENCES `projetoExpoCeep`.`projeto` (`idprojeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoExpoCeep`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoExpoCeep`.`aluno` (
  `idaluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `idprojeto` INT NOT NULL,
  PRIMARY KEY (`idaluno`),
  INDEX `fk_aluno_projeto1_idx` (`idprojeto` ASC),
  CONSTRAINT `fk_aluno_projeto1`
    FOREIGN KEY (`idprojeto`)
    REFERENCES `projetoExpoCeep`.`projeto` (`idprojeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
